### ISSUE TITLE
Complete spreadsheet for images/credits on website

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#630] opened 2022-02-26 20:36 UTC
Descriptions and credits

**Comment by faucomte97** [comment] 2022-03-03 10:46
@lauracumming Is this a duplicate of https://app.zenhub.com/workspaces/code-for-life-ux-5db8789ca7e95f00017a07df/issues/ocadotechnology/codeforlife-design/160 ?

**Closed** 2022-03-11 10:39 UTC
