### ISSUE TITLE
Issue labelling

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#379] opened 2021-01-13 12:29 UTC
We need to review and agree on the labelling on Zenhub as the design board hardly has any, and the others have too many.
Investigate existing examples of Kanban labelling.

**Comment by faucomte97** [comment] 2021-02-17 14:07
This seems to be a duplicate of #404 @lauracumming , closing

**Closed by faucomte97** 2021-02-17 14:07 UTC
