### ISSUE TITLE
Q's & A's test for Python coding club

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-admin#543] opened 2021-09-17 07:24 UTC
We are looking for 1 or 2 short quizzes to test knowledge throughout the coding club course that we can use as a pilot to introducing this format elsewhere on the site. An explanation of what it is testing for too.

**Comment by razvan-pro** [comment] 2021-09-20 09:36
duplicate of #534

**Closed by razvan-pro** 2021-09-20 09:36 UTC
